"""Train a depth-3 deep linear network on a binary-hierarchical task, using
Saxe, McClelland & Ganguli 2019 PNAS's ACTUAL generative model (SI Appendix,
"Hierarchical feature vectors from a branching diffusion process"), not a
hand-built idealized target: P=2^D items sit at the leaves of a depth-D
binary tree; each of n_features independent attributes is generated by a
root coin flip (+-1) propagated down the tree, flipping sign with
probability epsilon at each branch. The resulting (P, n_features) sampled
feature matrix IS the network's training target (output_dim=n_features),
and its empirical SVD (not a hand-built basis) gives the "ground truth"
modes used throughout the analysis -- this is the finite-sample, noisy
version of the exact Haar-wavelet task used earlier, which is only the
n_features -> infinity limit (see project memory for the SI verification).

Small random Gaussian init (Saxe et al. 2019 PNAS methodology -- see sim 2's
memory notes), same single-anchor-per-trial curriculum as sim 1/2/3.
"""
import os
import sys

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

import numpy as np
import torch

from sims.common.inputs import make_orthonormal_inputs
from sims.common.linear_net import DeepLinearNet
from sims.sim3_hierarchy.config import Sim3Config

DEFAULT_OUT_PATH = os.path.join(_PROJECT_ROOT, "outputs", "sim3_hierarchy", "results.npz")

L = 3  # network depth, matches DeepLinearNet


def haar_tree_wavelets(n_items: int, depth: int):
    """(n_modes, n_items) matrix of orthonormal, LOCALIZED +-1 tree wavelets
    (one per internal node of a balanced depth-D binary tree), plus a
    (n_modes,) array giving each wavelet's level (0=root/coarsest).

    Level lambda has 2**lambda wavelets, each covering a contiguous block of
    n_items / 2**lambda items (first half +, second half -, zero outside the
    block). n_modes = sum_{lambda=0}^{D-1} 2**lambda = 2**D - 1 = n_items - 1.
    Orthonormal by construction: same-level wavelets have disjoint support;
    different-level wavelets are either disjoint or nested, and a nested
    (finer) wavelet always sums to zero over the coarser wavelet's constant
    region, so their inner product is zero either way.
    """
    assert n_items == 2 ** depth, f"n_items ({n_items}) must equal 2**tree_depth ({2**depth})"
    wavelets, levels = [], []
    for lam in range(depth):
        n_nodes = 2 ** lam
        block_size = n_items // n_nodes
        half = block_size // 2
        c = 1.0 / np.sqrt(block_size)
        for node in range(n_nodes):
            start = node * block_size
            w = np.zeros(n_items)
            w[start:start + half] = c
            w[start + half:start + block_size] = -c
            wavelets.append(w)
            levels.append(lam)
    return np.array(wavelets), np.array(levels)


def branching_diffusion_features(n_items: int, depth: int, n_features: int,
                                  epsilon: float, seed: int) -> np.ndarray:
    """(n_items, n_features) matrix of +-1 features, each generated
    INDEPENDENTLY via Saxe et al.'s branching diffusion process: a root
    value +-1 (fair coin), propagated down `depth` binary-branching
    generations, flipping sign with probability `epsilon` at each step
    (each child's flip is its own independent draw). n_items must equal
    2**depth (a balanced binary tree). This exactly matches their SI
    Appendix algorithm and parameter (epsilon=0.15 for their own D=3
    binary-branching example).
    """
    assert n_items == 2 ** depth, f"n_items ({n_items}) must equal 2**depth ({2 ** depth})"
    rng = np.random.default_rng(seed)
    features = np.zeros((n_items, n_features), dtype=np.float64)
    for f in range(n_features):
        vals = rng.choice([-1.0, 1.0], size=1)
        for _ in range(depth):
            vals = np.repeat(vals, 2)
            flips = rng.random(vals.shape[0]) < epsilon
            vals = np.where(flips, -vals, vals)
        features[:, f] = vals
    return features


def empirical_modes(Y_items: np.ndarray, n_items: int, depth: int):
    """SVD of the sampled (n_items, n_features) feature matrix -- the
    "ground truth" modes for THIS specific finite sample, not a hand-built
    basis. Each of the (up to n_items) modes is labeled by matching it
    (cosine similarity, sign-agnostic since SVD vectors have arbitrary
    sign) against the idealized reference directions: the exact Haar
    wavelets for this tree plus the constant/"baseline" direction (the
    root level of the generative process is a single shared node, with no
    actual split, so it contributes a genuine baseline-similarity mode
    alongside the depth tree-split wavelets -- see project memory).

    Returns item_loadings (n_modes, n_items), feature_loadings
    (n_modes, n_features), singular_values (n_modes,), and labels
    (n_modes,) with -1=baseline/root, 0..depth-1=matched tree level.
    """
    U, s, Vt = np.linalg.svd(Y_items, full_matrices=False)
    item_loadings = U.T  # (n_modes, n_items)
    feature_loadings = Vt  # (n_modes, n_features)

    ideal_wavelets, ideal_levels = haar_tree_wavelets(n_items, depth)  # (n_items-1, n_items)
    ideal_const = np.ones(n_items) / np.sqrt(n_items)
    ideal_refs = np.vstack([ideal_const[None, :], ideal_wavelets])  # (n_items, n_items)
    ideal_labels = np.concatenate([[-1], ideal_levels])

    labels = np.zeros(len(s), dtype=np.int64)
    for alpha in range(len(s)):
        sims = np.abs(ideal_refs @ item_loadings[alpha])
        labels[alpha] = ideal_labels[np.argmax(sims)]
    return item_loadings, feature_loadings, s, labels


def tree_distance(i: int, anchor: int, depth: int, n_items: int) -> int:
    """Ultrametric tree distance: 0 iff i == anchor, 1 for anchor's closest
    possible distinct item (immediate sibling -- shares every level's block
    up to the finest split), depth for an item separated already at the
    root split (shares no level's block). Distance = depth + 1 - (number
    of levels item i and anchor share the same tree block), except for the
    i == anchor case (distance 0) which the level-sharing count can't
    distinguish from "sibling" on its own.
    """
    if i == anchor:
        return 0
    shared = 0
    for lam in range(depth):
        block_size = n_items // (2 ** lam)
        if i // block_size != anchor // block_size:
            break
        shared += 1
    return depth - shared + 1


def run(cfg: Sim3Config, out_path: str = DEFAULT_OUT_PATH) -> str:
    torch.manual_seed(cfg.seed)

    X = make_orthonormal_inputs(cfg.n_items, cfg.input_dim, seed=cfg.seed)  # (n_items, input_dim)
    ortho_err = (X @ X.T - torch.eye(cfg.n_items, dtype=X.dtype)).abs().max().item()
    assert ortho_err < 1e-5, f"inputs not orthonormal: max err {ortho_err}"

    Y_items = branching_diffusion_features(
        cfg.n_items, cfg.tree_depth, cfg.n_features, cfg.mutation_epsilon, seed=cfg.seed + 3
    )  # (n_items, n_features) -- the actual training target (row i = item i's sampled attribute vector)
    Y_items_t = torch.tensor(Y_items, dtype=torch.float64)

    V, feature_loadings, s, levels = empirical_modes(Y_items, cfg.n_items, cfg.tree_depth)
    n_modes = V.shape[0]

    # Small random Gaussian init, fan-in normalized, scaled by a0^(1/L) per
    # layer -- see sim 2's train.py for the full rationale (matches Saxe et
    # al. 2019 PNAS's actual methodology, not a deliberate alignment).
    scale = cfg.a0 ** (1.0 / L)
    net = DeepLinearNet(cfg.input_dim, cfg.h1_dim, cfg.h2_dim, output_dim=cfg.n_features, seed=cfg.seed)
    with torch.no_grad():
        g = torch.Generator().manual_seed(cfg.seed + 1)
        net.W1.weight.copy_(scale * torch.randn(net.W1.weight.shape, generator=g, dtype=torch.float64)
                             / (cfg.input_dim ** 0.5))
        net.W2.weight.copy_(scale * torch.randn(net.W2.weight.shape, generator=g, dtype=torch.float64)
                             / (cfg.h1_dim ** 0.5))
        net.W3.weight.copy_(scale * torch.randn(net.W3.weight.shape, generator=g, dtype=torch.float64)
                             / (cfg.h2_dim ** 0.5))

    optimizer = torch.optim.SGD(net.parameters(), lr=cfg.lr)

    T = cfg.n_trials
    h1_pre = np.zeros((T, cfg.n_items, cfg.h1_dim), dtype=np.float64)
    h1_post = np.zeros_like(h1_pre)
    h2_pre = np.zeros((T, cfg.n_items, cfg.h2_dim), dtype=np.float64)
    h2_post = np.zeros_like(h2_pre)
    y_pre = np.zeros((T, cfg.n_items, cfg.n_features), dtype=np.float64)
    y_post = np.zeros_like(y_pre)
    anchor_idx = np.zeros(T, dtype=np.int64)
    anchor_loss = np.zeros(T, dtype=np.float64)
    a_pre = np.zeros((T, n_modes), dtype=np.float64)  # learned mode amplitudes a_alpha(t)

    order_rng = np.random.default_rng(cfg.seed + 2)
    queue = []
    for trial in range(cfg.n_trials):
        if not queue:
            queue = list(order_rng.permutation(cfg.n_items))
        a = int(queue.pop(0))

        h1, h2, y = net(X)
        h1_pre[trial] = h1.detach().numpy()
        h2_pre[trial] = h2.detach().numpy()
        y_pre_np = y.detach().numpy()  # (n_items, n_features)
        y_pre[trial] = y_pre_np
        for alpha in range(n_modes):
            # bilinear projection onto mode alpha's item- and feature-loading
            # vectors (a_alpha(t) = u_alpha^T Y_hat(t) v_alpha) -- not a simple
            # column dot product, since output columns are raw sampled
            # features now, not pre-aligned per-mode amplitudes.
            a_pre[trial, alpha] = V[alpha] @ y_pre_np @ feature_loadings[alpha]

        loss = 0.5 * ((y[a] - Y_items_t[a]) ** 2).sum()
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        with torch.no_grad():
            h1_2, h2_2, y_2 = net(X)
        h1_post[trial] = h1_2.numpy()
        h2_post[trial] = h2_2.numpy()
        y_post[trial] = y_2.numpy()

        anchor_idx[trial] = a
        anchor_loss[trial] = loss.item()

        if (trial + 1) % max(1, cfg.n_trials // 10) == 0:
            window = max(1, cfg.n_items)
            recent = anchor_loss[max(0, trial + 1 - window):trial + 1].mean()
            level_means = [a_pre[trial, levels == lam].mean() for lam in range(cfg.tree_depth)]
            baseline_mean = a_pre[trial, levels == -1].mean() if np.any(levels == -1) else float("nan")
            print(f"trial {trial + 1}/{cfg.n_trials}  mean anchor loss (last {window}) = {recent:.5f}  "
                  f"level means = {np.round(level_means, 4)}  baseline mean = {baseline_mean:.4f}")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    np.savez_compressed(
        out_path,
        h1_pre=h1_pre, h1_post=h1_post,
        h2_pre=h2_pre, h2_post=h2_post,
        y_pre=y_pre, y_post=y_post,
        anchor_idx=anchor_idx, anchor_loss=anchor_loss,
        a_pre=a_pre,
        X=X.numpy(), V=V, feature_loadings=feature_loadings, levels=levels,
        singular_values=s, Y_items=Y_items,
        W1_final=net.W1.weight.detach().numpy(),
        W2_final=net.W2.weight.detach().numpy(),
        W3_final=net.W3.weight.detach().numpy(),
        n_items=cfg.n_items, tree_depth=cfg.tree_depth, input_dim=cfg.input_dim,
        h1_dim=cfg.h1_dim, h2_dim=cfg.h2_dim, n_modes=n_modes, n_features=cfg.n_features,
        mutation_epsilon=cfg.mutation_epsilon,
        a0=cfg.a0, lr=cfg.lr, n_trials=cfg.n_trials, seed=cfg.seed,
    )
    print(f"Saved results to {out_path}")
    return out_path


if __name__ == "__main__":
    run(Sim3Config())
